modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/TwistedGate/ImmersivePetroleum/issues"
license="All rights reserved"

[[mods]] #mandatory
	modId="immersivepetroleum"
	version="${version}"
	displayName="Immersive Petroleum"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/immersive-petroleum"
	authors="Flaxbeard and Maintained by TwistedGate."
	description="Adds oil and oil processing features to Immersive Engineering."
	logoFile="logo.png"
	updateJSONURL="https://raw.githubusercontent.com/TwistedGate/ImmersivePetroleum/changelogs/${mc_version}/change.json"
	#credits=""

[[dependencies.immersivepetroleum]]
	modId="immersiveengineering"
	mandatory=true
	versionRange="[${ie_version},)"
	ordering="BEFORE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="forge"
	mandatory=true
	versionRange="[${forge_version},)"
	ordering="NONE"
	side="BOTH"

[[dependencies.immersivepetroleum]]
	modId="minecraft"
	mandatory=true
	versionRange="[${mc_version}]"
	ordering="NONE"
	side="BOTH"
